### ISSUE TITLE
Any::Moose is deprecated in debian stretch

### ISSUE THREAD

**Issue by skrivy** [tokuhirom/p5-fcgi-client#1]
While upgrading our system, we have noticed this warning:

`Any::Moose is deprecated. Please use Moo instead at /root/test/FCGI/Client/Connection.pm line 2.`

It seems like this library is used in most of the parts of the FCGI library.

**Comment by guimard** [comment]
Fixed by 0.09. Thanks

**Comment by michal-josef-spacek** [comment]
@tokuhirom We could close this ticket.
